services:
  - type: web
    name: teamflow
    runtime: node
    rootDir: web
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PAYSTACK_SECRET_KEY
        sync: false
      - key: NEXT_PUBLIC_PAYSTACK_PUBLIC_KEY
        sync: false
      - key: NEXT_PUBLIC_APP_URL
        sync: false
      - key: PORT
        value: 3000
